name: todo_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  provider: ^6.0.3

dev_dependencies:
  build_runner: ^2.1.11
  hive_generator: ^1.1.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
